### ISSUE TITLE
Bad check value for FF in css-properties-case-insensitive_t01

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/co19#118]
This test has been suppressed due to a different bug, but in fixing that I notice that on Firefox it fails the very last test because the expectation is for "normal" (i.e. not bold) but instead it gets a value of "400". I think that value corresponds to not bold, but Firefox just isn't aliasing it.

**Comment by sgrekhov** [comment]
@alan-knight what version of the SDK contains fix of a different bug mentioned in the description? Dart VM version: 1.25.0-dev.7.0 (Mon Jul 17 02:58:18 2017) on "windows_x64" still failing before reaching very last check in the test

**Comment by alan-knight** [comment]
Fix landed at https://github.com/dart-lang/sdk/commit/789de57cdfe5649ac46b22f4a0fdcbfd6b93c5af , about 19 hours ago.

**Comment by sgrekhov** [comment]
This test is still failing for me at the very first check. Expect.equals(expected: <>, actual: <1904px>, 'getPropertyValue'). Seems that getPropertyValue() is not case insensitive for both Chrome and Firefox. Tested on Dart VM version: 1.25.0-dev.9.0 (Tue Aug 01 01:52:00 2017) on "windows_x64"
